name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: asharubendy
          password: ${{ secrets.GHCR }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64
          file: src/Dockerfile
          push: true
          tags: ghcr.io/asharubendy/aamirah-frontend:prod
          cache-from: type=gha
          cache-to: type=gha
